export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_PRODUCTS_BY_PRICE = "GET_PRODUCTS_BY_PRICE";
export const GET_PRODUCTS_BY_PRICE_AND_CATEGORY =
  "GET_PRODUCTS_BY_PRICE_AND_CATEGORY";
export const GET_PRODUCTS_BY_PRICE_AND_NAME = "GET_PRODUCTS_BY_PRICE_AND_NAME";
export const GET_PRODUCTS_BY_CATEGORY_AND_NAME =
  "GET_PRODUCTS_BY_CATEGORY_AND_NAME";
export const GET_PRODUCTS_BY_PRICE_AND_CATEGORY_AND_NAME =
  "GET_PRODUCTS_BY_PRICE_AND_CATEGORY_AND_NAME";
export const GET_PRODUCTS_BY_PRICE_AND_CATEGORY_AND_NAME_AND_PRICE =
  "GET_PRODUCTS_BY_PRICE_AND_CATEGORY_AND_NAME_AND_PRICE";
export const GET_PRODUCTS_BY_PRICE_AND_CATEGORY_AND_NAME_AND_PRICE_AND_CATEGORY =
  "GET_PRODUCTS_BY_PRICE_AND_CATEGORY_AND_NAME_AND_PRICE_AND_CATEGORY";

export const POST_PRODUCTS = "POST_PRODUCTS";

export const POST_USER = "POST_USER";

export const POST_LOGIN = "POST_LOGIN";

export const POST_LOGOUT = "POST_LOGOUT";

export const GET_PRODUCTS_ID = "GET_PRODUCTS_ID";
